# Create or update a template deployment based on a uri to the template and parameters specified inline.
---
- hosts: ansible-client
  tasks:
    - name: Creating Barracuda WAF using the Azure solution template
      azure_rm_deployment:
        state: present
        resource_group_name: ansible-aravindan1
        parameters:
          adminPassword:
            value: 1234567a!
          location:
            value: West US
          storageAccountName:
            value: ansiblearavindan2
          storageAccountType:
            value: Standard_LRS
          vmName:
            value: aravindanansible2
          vNETName:
            value: ara-prod
          addressPrefix:
            value: 10.0.0.0/16
          subnetPrefix:
            value: 10.0.0.0/24
          subnetName:
            value: default
          vmSize:
            value: Standard_D2
          publicIPAddressName:
            value: ansiblearavindanip2
          dnsNameForIP:
            value: wafonansibletest2
        template_link: 'https://raw.githubusercontent.com/barracudanetworks/waf-azure/master/ARMTemplates/mainTemplate-Barracuda-WAF-BYOL.json'
      register: azure